export interface IConfig {
    idUti: number,
    hdc1: number,
    hdc2: number,
    hdc3: number,
    hdc4: number,
    hdc5: number,
    hdc6: number,
    unite: number,
    correctionJour: number,
    correctionNuit: number,
    valeur: number,
    unite1: number,
    unite2: number,
    unite3: number,
    unite4: number,
    unite5: number,
    unite6: number,
    dureeAction: number
}
